import type maplibregl from 'maplibre-gl';

// Client-side PDF export. Uses browser-native canvas → jsPDF via CDN import.
// jsPDF is loaded on-demand to keep the initial bundle small.

async function loadJsPDF(): Promise<typeof import('jspdf')> {
  // Dynamic import — jspdf is added as a dependency for this feature.
  return await import('jspdf');
}

/** Capture the current map view and download it as a Letter-size PDF. */
export async function exportMapToPDF(map: maplibregl.Map): Promise<void> {
  // Trigger a fresh render so the WebGL canvas has current pixels.
  map.triggerRepaint();
  await new Promise((r) => requestAnimationFrame(() => r(null)));
  await new Promise((r) => setTimeout(r, 200));

  const canvas = map.getCanvas();
  const dataUrl = canvas.toDataURL('image/png');

  const { jsPDF } = await loadJsPDF();
  // Letter landscape — 11 × 8.5 inches (792 × 612 pt)
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'letter' });

  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 32;

  // Header
  pdf.setFillColor(22, 163, 74); // green-600
  pdf.rect(0, 0, pageW, 42, 'F');
  pdf.setTextColor('#ffffff');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text('ROAM Map Export', margin, 28);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  const now = new Date().toLocaleString();
  const c = map.getCenter();
  const z = map.getZoom();
  pdf.text(`${now}  ·  center ${c.lat.toFixed(4)}, ${c.lng.toFixed(4)}  ·  z${z.toFixed(1)}`, pageW - margin, 28, { align: 'right' });

  // Fit the image into the available area, preserving aspect
  const availW = pageW - margin * 2;
  const availH = pageH - 42 - margin - 20;
  const imgAspect = canvas.width / canvas.height;
  let drawW = availW;
  let drawH = drawW / imgAspect;
  if (drawH > availH) {
    drawH = availH;
    drawW = drawH * imgAspect;
  }
  const drawX = (pageW - drawW) / 2;
  const drawY = 42 + margin;
  pdf.addImage(dataUrl, 'PNG', drawX, drawY, drawW, drawH);

  // Footer
  pdf.setTextColor('#57534e');
  pdf.setFontSize(8);
  pdf.text('© OpenStreetMap, OpenFreeMap, OSMU. Generated by roam.danmarzari.com', margin, pageH - 12);

  const filename = `roam-map-${new Date().toISOString().slice(0, 10)}.pdf`;
  pdf.save(filename);
}
